// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldOAuthID holds the string denoting the oauthid field in the database.
	FieldOAuthID = "oauth_id"
	// FieldSessionToken holds the string denoting the sessiontoken field in the database.
	FieldSessionToken = "session_token"
	// FieldIsActivated holds the string denoting the isactivated field in the database.
	FieldIsActivated = "is_activated"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldOAuthID,
	FieldSessionToken,
	FieldIsActivated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "Name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSessionToken holds the default value on creation for the "SessionToken" field.
	DefaultSessionToken func() string
	// SessionTokenValidator is a validator for the "SessionToken" field. It is called by the builders before save.
	SessionTokenValidator func(string) error
	// DefaultIsActivated holds the default value on creation for the "IsActivated" field.
	DefaultIsActivated bool
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByOAuthID orders the results by the OAuthID field.
func ByOAuthID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOAuthID, opts...).ToFunc()
}

// BySessionToken orders the results by the SessionToken field.
func BySessionToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionToken, opts...).ToFunc()
}

// ByIsActivated orders the results by the IsActivated field.
func ByIsActivated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActivated, opts...).ToFunc()
}
