package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/koalatea/go-project-skeleton/graphql/generated"
)

// ExampleMutation is the resolver for the exampleMutation field.
func (r *mutationResolver) ExampleMutation(ctx context.Context, arg1 string, arg2 string) (string, error) {
	panic(fmt.Errorf("not implemented: ExampleMutation - exampleMutation"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
